import { NodeVisibility, PlaygroundNodeKind } from "@prisma/client";
import { clampString } from "@/lib/security";

/**
 * Validation for canvas op payloads.
 *
 * Hand-rolled predicates in the same style as the `parseEnum` helpers in
 * @/lib/content-authz, rather than a schema-validation dependency. The surface
 * is small and fixed — a dozen numeric fields and three enums — and the repo has
 * no runtime validator today; adding one for this would be the tail wagging the
 * dog.
 *
 * Everything here treats its input as hostile JSON. A canvas op arrives from a
 * browser and is written straight into a shared room, so an unbounded string or
 * a NaN coordinate is a denial-of-service on everyone else in the meeting.
 */

/** Longest node body we persist. Beyond this the canvas is the wrong tool. */
export const MAX_NODE_TEXT = 8000;
/** Cap on the kind-specific JSON payload, serialised. */
export const MAX_NODE_DATA_BYTES = 64_000;
/**
 * World-coordinate bound. Generous enough that no real board reaches it, small
 * enough that a hostile value cannot produce a canvas the browser cannot lay
 * out — Infinity here becomes an unrecoverable room for every participant.
 */
export const MAX_WORLD_COORD = 1_000_000;
export const MIN_NODE_DIMENSION = 8;
export const MAX_NODE_DIMENSION = 20_000;

export function parseNodeKind(value: unknown): PlaygroundNodeKind | undefined {
  if (typeof value !== "string") return undefined;
  return Object.values(PlaygroundNodeKind).includes(value as PlaygroundNodeKind)
    ? (value as PlaygroundNodeKind)
    : undefined;
}

export function parseVisibility(value: unknown): NodeVisibility | undefined {
  if (typeof value !== "string") return undefined;
  return Object.values(NodeVisibility).includes(value as NodeVisibility)
    ? (value as NodeVisibility)
    : undefined;
}

/**
 * A finite, bounded coordinate.
 *
 * Rejects NaN and Infinity explicitly: both survive `typeof x === "number"`,
 * both serialise through JSON as `null` on the way back out, and both make a
 * node permanently unselectable because every hit test against them is false.
 */
export function parseCoord(value: unknown): number | undefined {
  if (typeof value !== "number" || !Number.isFinite(value)) return undefined;
  if (Math.abs(value) > MAX_WORLD_COORD) return undefined;
  return value;
}

export function parseDimension(value: unknown): number | undefined {
  if (typeof value !== "number" || !Number.isFinite(value)) return undefined;
  if (value < MIN_NODE_DIMENSION || value > MAX_NODE_DIMENSION) return undefined;
  return value;
}

export function parseZ(value: unknown): number | undefined {
  if (typeof value !== "number" || !Number.isInteger(value)) return undefined;
  if (Math.abs(value) > 1_000_000) return undefined;
  return value;
}

/** A non-negative integer version, as sent with a discrete op. */
export function parseVersion(value: unknown): number | undefined {
  if (typeof value !== "number" || !Number.isInteger(value) || value < 0) {
    return undefined;
  }
  return value;
}

/** Node text, trimmed and hard-capped. Never null-vs-empty ambiguous. */
export function parseNodeText(value: unknown): string | null {
  if (value === null || value === undefined) return null;
  if (typeof value !== "string") return null;
  const text = clampString(value, MAX_NODE_TEXT);
  return text.length > 0 ? text : null;
}

/**
 * A kind-specific JSON payload.
 *
 * Must be a plain object — arrays and primitives are rejected because Prisma's
 * Json column would accept them and every reader downstream assumes an object.
 * Size is checked against the SERIALISED form, since that is what actually hits
 * the database and the SSE fan-out.
 */
export function parseNodeJson(value: unknown): Record<string, unknown> | undefined {
  if (value === null || value === undefined) return {};
  if (typeof value !== "object" || Array.isArray(value)) return undefined;

  let serialised: string;
  try {
    serialised = JSON.stringify(value);
  } catch {
    // Circular structures reach here.
    return undefined;
  }
  if (serialised.length > MAX_NODE_DATA_BYTES) return undefined;

  return value as Record<string, unknown>;
}

/**
 * A client-minted node id.
 *
 * Required to be a UUID: ids are generated by the browser so that an edge can
 * reference its endpoints before any round trip, which means the server cannot
 * assume they are well-formed. Constraining the shape keeps them index-friendly
 * and stops a client planting an id that collides with a cuid.
 */
const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

export function parseNodeId(value: unknown): string | undefined {
  if (typeof value !== "string") return undefined;
  return UUID_RE.test(value) ? value : undefined;
}

/** Idempotency key for an op. Same shape rule, same reasoning. */
export function parseClientOpId(value: unknown): string | undefined {
  return parseNodeId(value);
}
