-- AlterTable
ALTER TABLE "HomePageContent" ALTER COLUMN "heroSubtitle1En" SET NOT NULL,
ALTER COLUMN "heroSubtitle1Ar" SET NOT NULL,
ALTER COLUMN "heroSubtitle1He" SET NOT NULL,
ALTER COLUMN "heroSubtitle2En" SET NOT NULL,
ALTER COLUMN "heroSubtitle2Ar" SET NOT NULL,
ALTER COLUMN "heroSubtitle2He" SET NOT NULL,
ALTER COLUMN "heroStatsEn" SET NOT NULL,
ALTER COLUMN "heroStatsAr" SET NOT NULL,
ALTER COLUMN "heroStatsHe" SET NOT NULL,
ALTER COLUMN "aboutBadgeEn" SET NOT NULL,
ALTER COLUMN "aboutBadgeAr" SET NOT NULL,
ALTER COLUMN "aboutBadgeHe" SET NOT NULL,
ALTER COLUMN "aboutHeadingEn" SET NOT NULL,
ALTER COLUMN "aboutHeadingAr" SET NOT NULL,
ALTER COLUMN "aboutHeadingHe" SET NOT NULL,
ALTER COLUMN "aboutParagraph1En" SET NOT NULL,
ALTER COLUMN "aboutParagraph1En" SET DEFAULT 'Paxala Media Production is a full-service creative agency with in-house production, built to shape, scale, and elevate brands through strategic visual storytelling.',
ALTER COLUMN "aboutParagraph1Ar" SET NOT NULL,
ALTER COLUMN "aboutParagraph1Ar" SET DEFAULT 'Paxala Media Production is a full-service creative agency with in-house production, built to shape, scale, and elevate brands through strategic visual storytelling.',
ALTER COLUMN "aboutParagraph1He" SET NOT NULL,
ALTER COLUMN "aboutParagraph1He" SET DEFAULT 'Paxala Media Production is a full-service creative agency with in-house production, built to shape, scale, and elevate brands through strategic visual storytelling.',
ALTER COLUMN "aboutParagraph2En" SET NOT NULL,
ALTER COLUMN "aboutParagraph2En" SET DEFAULT 'What began as a passion-driven studio has evolved into a multidisciplinary creative house that leads with strategy and creative direction, while executing everything under one roof — from branding and content to film, digital, and growth.',
ALTER COLUMN "aboutParagraph2Ar" SET NOT NULL,
ALTER COLUMN "aboutParagraph2Ar" SET DEFAULT 'What began as a passion-driven studio has evolved into a multidisciplinary creative house that leads with strategy and creative direction, while executing everything under one roof — from branding and content to film, digital, and growth.',
ALTER COLUMN "aboutParagraph2He" SET NOT NULL,
ALTER COLUMN "aboutParagraph2He" SET DEFAULT 'What began as a passion-driven studio has evolved into a multidisciplinary creative house that leads with strategy and creative direction, while executing everything under one roof — from branding and content to film, digital, and growth.',
ALTER COLUMN "aboutParagraph3En" SET NOT NULL,
ALTER COLUMN "aboutParagraph3En" SET DEFAULT 'Every project is led under a single creative direction and executed through a fully integrated in-house system — ensuring clarity, consistency, and control from strategy to final delivery.',
ALTER COLUMN "aboutParagraph3Ar" SET NOT NULL,
ALTER COLUMN "aboutParagraph3Ar" SET DEFAULT 'Every project is led under a single creative direction and executed through a fully integrated in-house system — ensuring clarity, consistency, and control from strategy to final delivery.',
ALTER COLUMN "aboutParagraph3He" SET NOT NULL,
ALTER COLUMN "aboutParagraph3He" SET DEFAULT 'Every project is led under a single creative direction and executed through a fully integrated in-house system — ensuring clarity, consistency, and control from strategy to final delivery.',
ALTER COLUMN "aboutParagraph4En" SET NOT NULL,
ALTER COLUMN "aboutParagraph4En" SET DEFAULT 'We partner with ambitious brands, institutions, and companies that understand visuals are not decoration — they are a business asset.',
ALTER COLUMN "aboutParagraph4Ar" SET NOT NULL,
ALTER COLUMN "aboutParagraph4Ar" SET DEFAULT 'We partner with ambitious brands, institutions, and companies that understand visuals are not decoration — they are a business asset.',
ALTER COLUMN "aboutParagraph4He" SET NOT NULL,
ALTER COLUMN "aboutParagraph4He" SET DEFAULT 'We partner with ambitious brands, institutions, and companies that understand visuals are not decoration — they are a business asset.',
ALTER COLUMN "aboutParagraph5En" SET NOT NULL,
ALTER COLUMN "aboutParagraph5En" SET DEFAULT 'At PMP, we don''t just produce content. We build visual systems that tell stories, build trust, and drive results.',
ALTER COLUMN "aboutParagraph5Ar" SET NOT NULL,
ALTER COLUMN "aboutParagraph5Ar" SET DEFAULT 'At PMP, we don''t just produce content. We build visual systems that tell stories, build trust, and drive results.',
ALTER COLUMN "aboutParagraph5He" SET NOT NULL,
ALTER COLUMN "aboutParagraph5He" SET DEFAULT 'At PMP, we don''t just produce content. We build visual systems that tell stories, build trust, and drive results.',
ALTER COLUMN "aboutHighlightsEn" SET NOT NULL,
ALTER COLUMN "aboutHighlightsEn" SET DEFAULT '["Full-service creative agency","Expert team of filmmakers & designers","Cutting-edge equipment & technology","End-to-end project management","Dedicated to client success"]',
ALTER COLUMN "aboutHighlightsAr" SET NOT NULL,
ALTER COLUMN "aboutHighlightsAr" SET DEFAULT '["Full-service creative agency","Expert team of filmmakers & designers","Cutting-edge equipment & technology","End-to-end project management","Dedicated to client success"]',
ALTER COLUMN "aboutHighlightsHe" SET NOT NULL,
ALTER COLUMN "aboutHighlightsHe" SET DEFAULT '["Full-service creative agency","Expert team of filmmakers & designers","Cutting-edge equipment & technology","End-to-end project management","Dedicated to client success"]',
ALTER COLUMN "aboutYearsTextEn" SET NOT NULL,
ALTER COLUMN "aboutYearsTextAr" SET NOT NULL,
ALTER COLUMN "aboutYearsTextHe" SET NOT NULL,
ALTER COLUMN "aboutYearsLabelEn" SET NOT NULL,
ALTER COLUMN "aboutYearsLabelAr" SET NOT NULL,
ALTER COLUMN "aboutYearsLabelHe" SET NOT NULL,
ALTER COLUMN "teamSubtitleEn" SET NOT NULL,
ALTER COLUMN "teamSubtitleAr" SET NOT NULL,
ALTER COLUMN "teamSubtitleHe" SET NOT NULL,
ALTER COLUMN "teamTitleEn" SET NOT NULL,
ALTER COLUMN "teamTitleAr" SET NOT NULL,
ALTER COLUMN "teamTitleHe" SET NOT NULL,
ALTER COLUMN "teamDescriptionEn" SET NOT NULL,
ALTER COLUMN "teamDescriptionEn" SET DEFAULT 'Meet the talented professionals behind our creative productions.',
ALTER COLUMN "teamDescriptionAr" SET NOT NULL,
ALTER COLUMN "teamDescriptionAr" SET DEFAULT 'Meet the talented professionals behind our creative productions.',
ALTER COLUMN "teamDescriptionHe" SET NOT NULL,
ALTER COLUMN "teamDescriptionHe" SET DEFAULT 'Meet the talented professionals behind our creative productions.',
ALTER COLUMN "teamTab1LabelEn" SET NOT NULL,
ALTER COLUMN "teamTab1LabelAr" SET NOT NULL,
ALTER COLUMN "teamTab1LabelHe" SET NOT NULL,
ALTER COLUMN "teamTab2LabelEn" SET NOT NULL,
ALTER COLUMN "teamTab2LabelAr" SET NOT NULL,
ALTER COLUMN "teamTab2LabelHe" SET NOT NULL,
ALTER COLUMN "teamTab3LabelEn" SET NOT NULL,
ALTER COLUMN "teamTab3LabelAr" SET NOT NULL,
ALTER COLUMN "teamTab3LabelHe" SET NOT NULL,
ALTER COLUMN "clientsSubtitleEn" SET NOT NULL,
ALTER COLUMN "clientsSubtitleAr" SET NOT NULL,
ALTER COLUMN "clientsSubtitleHe" SET NOT NULL,
ALTER COLUMN "clientsTitleEn" SET NOT NULL,
ALTER COLUMN "clientsTitleAr" SET NOT NULL,
ALTER COLUMN "clientsTitleHe" SET NOT NULL,
ALTER COLUMN "clientsDescriptionEn" SET NOT NULL,
ALTER COLUMN "clientsDescriptionEn" SET DEFAULT 'We''ve had the privilege of working with amazing brands and businesses.',
ALTER COLUMN "clientsDescriptionAr" SET NOT NULL,
ALTER COLUMN "clientsDescriptionAr" SET DEFAULT 'We''ve had the privilege of working with amazing brands and businesses.',
ALTER COLUMN "clientsDescriptionHe" SET NOT NULL,
ALTER COLUMN "clientsDescriptionHe" SET DEFAULT 'We''ve had the privilege of working with amazing brands and businesses.',
ALTER COLUMN "clientsWhatTheySayEn" SET NOT NULL,
ALTER COLUMN "clientsWhatTheySayAr" SET NOT NULL,
ALTER COLUMN "clientsWhatTheySayHe" SET NOT NULL,
ALTER COLUMN "ctaBadgeEn" SET NOT NULL,
ALTER COLUMN "ctaBadgeAr" SET NOT NULL,
ALTER COLUMN "ctaBadgeHe" SET NOT NULL,
ALTER COLUMN "ctaHeadingEn" SET NOT NULL,
ALTER COLUMN "ctaHeadingAr" SET NOT NULL,
ALTER COLUMN "ctaHeadingHe" SET NOT NULL,
ALTER COLUMN "ctaSubtitleEn" SET NOT NULL,
ALTER COLUMN "ctaSubtitleEn" SET DEFAULT 'Let''s create something amazing together. Book a consultation or get in touch to discuss your next project.',
ALTER COLUMN "ctaSubtitleAr" SET NOT NULL,
ALTER COLUMN "ctaSubtitleAr" SET DEFAULT 'Let''s create something amazing together. Book a consultation or get in touch to discuss your next project.',
ALTER COLUMN "ctaSubtitleHe" SET NOT NULL,
ALTER COLUMN "ctaSubtitleHe" SET DEFAULT 'Let''s create something amazing together. Book a consultation or get in touch to discuss your next project.',
ALTER COLUMN "aboutPageHeroBadgeEn" SET NOT NULL,
ALTER COLUMN "aboutPageHeroBadgeAr" SET NOT NULL,
ALTER COLUMN "aboutPageHeroBadgeHe" SET NOT NULL,
ALTER COLUMN "aboutPageHeroHeadingEn" SET NOT NULL,
ALTER COLUMN "aboutPageHeroHeadingAr" SET NOT NULL,
ALTER COLUMN "aboutPageHeroHeadingHe" SET NOT NULL,
ALTER COLUMN "aboutValuesSubtitleEn" SET NOT NULL,
ALTER COLUMN "aboutValuesSubtitleAr" SET NOT NULL,
ALTER COLUMN "aboutValuesSubtitleHe" SET NOT NULL,
ALTER COLUMN "aboutValuesTitleEn" SET NOT NULL,
ALTER COLUMN "aboutValuesTitleAr" SET NOT NULL,
ALTER COLUMN "aboutValuesTitleHe" SET NOT NULL,
ALTER COLUMN "aboutValuesDescriptionEn" SET NOT NULL,
ALTER COLUMN "aboutValuesDescriptionEn" SET DEFAULT 'The principles that guide everything we do at Paxala Media.',
ALTER COLUMN "aboutValuesDescriptionAr" SET NOT NULL,
ALTER COLUMN "aboutValuesDescriptionAr" SET DEFAULT 'The principles that guide everything we do at Paxala Media.',
ALTER COLUMN "aboutValuesDescriptionHe" SET NOT NULL,
ALTER COLUMN "aboutValuesDescriptionHe" SET DEFAULT 'The principles that guide everything we do at Paxala Media.',
ALTER COLUMN "aboutValuesEn" SET NOT NULL,
ALTER COLUMN "aboutValuesEn" SET DEFAULT '[{"icon":"Target","title":"Excellence","description":"We strive for excellence in every project, paying attention to the smallest details to deliver outstanding results."},{"icon":"Users","title":"Collaboration","description":"We believe in the power of teamwork, both within our crew and with our clients, to create something truly remarkable."},{"icon":"Heart","title":"Passion","description":"Our passion for visual storytelling drives us to push creative boundaries and explore new possibilities."},{"icon":"Award","title":"Innovation","description":"We embrace new technologies and techniques to stay at the forefront of the creative industry."}]',
ALTER COLUMN "aboutValuesAr" SET NOT NULL,
ALTER COLUMN "aboutValuesAr" SET DEFAULT '[{"icon":"Target","title":"Excellence","description":"We strive for excellence in every project, paying attention to the smallest details to deliver outstanding results."},{"icon":"Users","title":"Collaboration","description":"We believe in the power of teamwork, both within our crew and with our clients, to create something truly remarkable."},{"icon":"Heart","title":"Passion","description":"Our passion for visual storytelling drives us to push creative boundaries and explore new possibilities."},{"icon":"Award","title":"Innovation","description":"We embrace new technologies and techniques to stay at the forefront of the creative industry."}]',
ALTER COLUMN "aboutValuesHe" SET NOT NULL,
ALTER COLUMN "aboutValuesHe" SET DEFAULT '[{"icon":"Target","title":"Excellence","description":"We strive for excellence in every project, paying attention to the smallest details to deliver outstanding results."},{"icon":"Users","title":"Collaboration","description":"We believe in the power of teamwork, both within our crew and with our clients, to create something truly remarkable."},{"icon":"Heart","title":"Passion","description":"Our passion for visual storytelling drives us to push creative boundaries and explore new possibilities."},{"icon":"Award","title":"Innovation","description":"We embrace new technologies and techniques to stay at the forefront of the creative industry."}]',
ALTER COLUMN "aboutMilestonesSubtitleEn" SET NOT NULL,
ALTER COLUMN "aboutMilestonesSubtitleAr" SET NOT NULL,
ALTER COLUMN "aboutMilestonesSubtitleHe" SET NOT NULL,
ALTER COLUMN "aboutMilestonesTitleEn" SET NOT NULL,
ALTER COLUMN "aboutMilestonesTitleAr" SET NOT NULL,
ALTER COLUMN "aboutMilestonesTitleHe" SET NOT NULL,
ALTER COLUMN "aboutMilestonesDescriptionEn" SET NOT NULL,
ALTER COLUMN "aboutMilestonesDescriptionEn" SET DEFAULT 'Key moments in our growth as a creative studio.',
ALTER COLUMN "aboutMilestonesDescriptionAr" SET NOT NULL,
ALTER COLUMN "aboutMilestonesDescriptionAr" SET DEFAULT 'Key moments in our growth as a creative studio.',
ALTER COLUMN "aboutMilestonesDescriptionHe" SET NOT NULL,
ALTER COLUMN "aboutMilestonesDescriptionHe" SET DEFAULT 'Key moments in our growth as a creative studio.',
ALTER COLUMN "aboutMilestonesEn" SET NOT NULL,
ALTER COLUMN "aboutMilestonesEn" SET DEFAULT '[{"year":"2014","title":"Founded","description":"Paxala Media was born from a passion for visual storytelling"},{"year":"2016","title":"First Major Client","description":"Completed our first major commercial project"},{"year":"2018","title":"Team Expansion","description":"Grew our team of creative professionals"},{"year":"2020","title":"Studio Launch","description":"Opened our dedicated production studio"},{"year":"2022","title":"Digital Services","description":"Expanded into web and app development"},{"year":"2024","title":"1000+ Projects","description":"Celebrated completing over 1000 client projects"}]',
ALTER COLUMN "aboutMilestonesAr" SET NOT NULL,
ALTER COLUMN "aboutMilestonesAr" SET DEFAULT '[{"year":"2014","title":"Founded","description":"Paxala Media was born from a passion for visual storytelling"},{"year":"2016","title":"First Major Client","description":"Completed our first major commercial project"},{"year":"2018","title":"Team Expansion","description":"Grew our team of creative professionals"},{"year":"2020","title":"Studio Launch","description":"Opened our dedicated production studio"},{"year":"2022","title":"Digital Services","description":"Expanded into web and app development"},{"year":"2024","title":"1000+ Projects","description":"Celebrated completing over 1000 client projects"}]',
ALTER COLUMN "aboutMilestonesHe" SET NOT NULL,
ALTER COLUMN "aboutMilestonesHe" SET DEFAULT '[{"year":"2014","title":"Founded","description":"Paxala Media was born from a passion for visual storytelling"},{"year":"2016","title":"First Major Client","description":"Completed our first major commercial project"},{"year":"2018","title":"Team Expansion","description":"Grew our team of creative professionals"},{"year":"2020","title":"Studio Launch","description":"Opened our dedicated production studio"},{"year":"2022","title":"Digital Services","description":"Expanded into web and app development"},{"year":"2024","title":"1000+ Projects","description":"Celebrated completing over 1000 client projects"}]',
ALTER COLUMN "aboutTeamSubtitleEn" SET NOT NULL,
ALTER COLUMN "aboutTeamSubtitleAr" SET NOT NULL,
ALTER COLUMN "aboutTeamSubtitleHe" SET NOT NULL,
ALTER COLUMN "aboutTeamTitleEn" SET NOT NULL,
ALTER COLUMN "aboutTeamTitleAr" SET NOT NULL,
ALTER COLUMN "aboutTeamTitleHe" SET NOT NULL,
ALTER COLUMN "aboutTeamDescriptionEn" SET NOT NULL,
ALTER COLUMN "aboutTeamDescriptionEn" SET DEFAULT 'The talented professionals behind our creative productions.',
ALTER COLUMN "aboutTeamDescriptionAr" SET NOT NULL,
ALTER COLUMN "aboutTeamDescriptionAr" SET DEFAULT 'The talented professionals behind our creative productions.',
ALTER COLUMN "aboutTeamDescriptionHe" SET NOT NULL,
ALTER COLUMN "aboutTeamDescriptionHe" SET DEFAULT 'The talented professionals behind our creative productions.',
ALTER COLUMN "aboutCtaHeadingEn" SET NOT NULL,
ALTER COLUMN "aboutCtaHeadingAr" SET NOT NULL,
ALTER COLUMN "aboutCtaHeadingHe" SET NOT NULL,
ALTER COLUMN "aboutCtaSubtitleEn" SET NOT NULL,
ALTER COLUMN "aboutCtaSubtitleEn" SET DEFAULT 'Let''s collaborate and create something extraordinary together. Our team is excited to hear about your project.',
ALTER COLUMN "aboutCtaSubtitleAr" SET NOT NULL,
ALTER COLUMN "aboutCtaSubtitleAr" SET DEFAULT 'Let''s collaborate and create something extraordinary together. Our team is excited to hear about your project.',
ALTER COLUMN "aboutCtaSubtitleHe" SET NOT NULL,
ALTER COLUMN "aboutCtaSubtitleHe" SET DEFAULT 'Let''s collaborate and create something extraordinary together. Our team is excited to hear about your project.';

